### ISSUE TITLE
Stop working after update from 0.0.4 to 1.0.0

### ISSUE THREAD

**Issue by JoaquinMembrado** [mudin/vue-global-var#1]
After update from 0.0.4 to 1.0.0 i have this error:

vue.runtime.esm.js:619 [Vue warn]: Property or method "$app" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property

If I go back to 0.0.4, then it works fine. This is what I have in my main.js:

Vue.use(VueGlobalVariable, {
  globals: {
    app: { 
      user: null
    }
  }
});

**Comment by mudin** [comment]
@JoaquinMembrado Sorry for late replay, I didn't see your message. after version one, prefix`$` is not automatically added, you need to add your self or use without `$`.
```
Vue.use(VueGlobalVariable, {
  globals: {
    $app: {
      user: null
    }
  }
});
```

**Comment by JoaquinMembrado** [comment]
Great!! Thank's! Now works fine.

**Comment by mudin** [comment]
@JoaquinMembrado You're welcome!
