### ISSUE TITLE
Doesn't work with Quasar

### ISSUE THREAD

**Issue by rachitpant** [mudin/vue-global-var#2]
I get a Vue warning
```
vue.runtime.esm.js?2b0e:587 [Vue warn]: Computed property "$appOpen" was assigned to but it has no setter.

found in

---> <App> at src/App.vue
       <Root>
```

In the same file , App.vue , I am earlier initializing the plugin as 
```
import VueGlobalVariable from 'vue-global-var'
/* global device */

Vue.use(VueGlobalVariable, {
  globals: {
    $appOpen: true
  }
})
```
,
Within the event handler below, when I try to set a value , I can see the already initialized value , but am unable to change the value , I get the above warning and after that I am not able to update it.
I am using quasar framework , ( The device ready event below is part of cordova )
```
var _this = this
    document.addEventListener('deviceready', () => {
      console.log('device ready fired')
      _this.$appOpen = true
```

**Comment by mudin** [comment]
what version are you using?

**Comment by insign** [comment]
It happened here too, but only when I use the name `$store`, others names even beginning with $, works fine.

```
[Vue warn]: Computed property "$store" was assigned to but it has no setter.

found in

---> <QPage>
       <Index> at src/pages/index.vue
         <QPageContainer>
           <QLayout>
             <MainLayout> at src/layouts/main-layout.vue
               <Ck> at src/App.vue
                 <Root>
```

**BTW, even with the error, it is working.**

Quasar Framework 1.9.1
