### ISSUE TITLE
How to set global variable from component

### ISSUE THREAD

**Issue by clintonnzedimma** [mudin/vue-global-var#3]
I would love to know how to set global or or override global variable in a component. 
Example in **main.js**,  i initialize
`Vue.use(VueGlobalVariable, {
	globals: {
			appName : 'FLIMBIT',
			userIsLoggedIn : false
	}
});`

Lets say in Index component, i set `this.userIsLoggedIn = true`  and i route to Profile component,  i want to access `this.userIsLoggedIn` to be `true` as well

**Comment by AbdallaMohammed** [comment]
Any idea how to do this ?

**Comment by niceque** [comment]
same question
