### ISSUE TITLE
How to set a global variable?

### ISSUE THREAD

**Issue by niceque** [mudin/vue-global-var#4]
In example, i have

`
Vue.use(VueGlobalVar, {
    globals: {
        workflowData: {
            test: '123',
        }
    },
});
`

and wanna set reactively with
`this.$set(this.workflowData,'test','456');` from any other component or `this.workflowData.test = '456'`
so this not working reactively, i can see changes only after rerendering component

while `v-model="workflowData.test"` works reactively

what i'm doin wrong? thx

**Comment by quiquelhappy** [comment]
I have the same question. How do you set a global variable correctly? Thanks.

**Comment by hjiul** [comment]
same question, do i have to create a setter in computed properties ?

**Comment by quiquelhappy** [comment]
I would suggest creating a global variable with Vue.prototype.$name = new Class();
and create a class with
class Class {

}
and code getters and setters there while no one is giving support to this question.

**Comment by mudin** [comment]
@niceque you dont need to use `this.$set`. 
it is better to create a class, such as `WorkflowData.js`:
```
class WorkflowData {
 constructor(options) {
  this.test = options.test;  // reactive
  // ...
 }
}
```

then in your `main.js` for example:

```
const $workflowData: new WorkflowData({
 test: '123'
});

Vue.use(VueGlobalVar, {
 globals: {
     $workflowData
   }
}
```

you can use `$workflowData` in any component, and its field `test` will be reactive.
Add more reactive fields in the class contructor
